. e add test reports

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,9 +30,20 @@ jobs:
     
     - name: Build
       run: go build -v ./...
+
+    - name: Install gotestsum
+      run: go install gotest.tools/gotestsum@latest
     
     - name: test
-      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
+      run: |
+        mkdir test-reports
+        gotestsum --junitfile test-reports/test-results.xml ./... -race -coverprofile=coverage.txt -covermode=atomic
+    
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/test-reports/*.xml'
   auto-merge:
     needs: build-and-test
     runs-on: ubuntu-latest
